spring.application.name=nutrition-analysis-service
server.port=8083

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/nutrition_db

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Fila
rabbitmq.queue.feed=feed.queue
rabbitmq.exchange.feed=feed.exchange
rabbitmq.routing-key.feed=feed.routing-key

# URL do feed-cost-service
feedcost.service.url=http://localhost:8082
